### ISSUE TITLE
Brightness Augmentation issue

### ISSUE THREAD

**Issue by calicratis19** [vxy10/p5_VehicleDetection_Unet#2]
Brightness Augmentation is done by scaling. Sometimes the value might get more than 255 and then will be set to scaledValue%256 which is erroneous.  The following is one way to solve this problem,

```
def RandomBrightness(img):
    img = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    h, s, v = cv2.split(img)

    scale = random.uniform(1, 1.5)

    v = np.clip(v * scale, 0, 255, out=v)
    img = cv2.merge((h, s, v))
    img = cv2.cvtColor(img, cv2.COLOR_HSV2RGB)
    return img
```

**Comment by vxy10** [comment]
yeah, i changed it in my implementation, forgot to update on github.
